Mock/giphy repository
frinyvonnick/laragif pull request #13
Opened 2017-04-15 22:23 UTC by frinyvonnick

J'ai testé en coupant ma connexion internet par contre le chargement devient extrêmement long. Je pense que c'est à cause du timeout de ma tentative de requête vers Giphy 😢

2017-04-15 22:30 UTC, frinyvonnick commented
A priori mon dernier commit résout les problèmes de lenteur 😸

2017-04-15 22:47 UTC, ptitFicus requested changes
Je pense que les fichiers d'images seraient mieux dans assets que dans public, vu que tout le contenu du dossier public est généré automatiquement par le process de build js.

2017-04-16 15:34 UTC, frinyvonnick commented
Il semblerait que le dossier public soit le bon endroit selon la documentation https://laravel.com/docs/5.4/structure#the-public-directory 👍

2017-04-16 19:44 UTC, ptitFicus approved these changes

2017-04-16 20:43 UTC, merged