Search frontend
frinyvonnick/laragif pull request #20
Opened 2017-04-20 22:45 UTC by ptitFicus

2017-04-23 08:04 UTC, frinyvonnick requested changes

2017-04-23 08:04 UTC, frinyvonnick commented on resources/assets/js/components/Application.vue
> +      console.log(`starting search for ${searchTerm}`)
Faut enlever les console.log non 😄 ?

2017-04-23 08:04 UTC, frinyvonnick commented on resources/assets/js/components/SearchBar.vue
> +        this.$emit('search', newValue)
Pas mal comme système !

2017-04-23 08:04 UTC, frinyvonnick commented on resources/assets/js/components/SearchResult.vue
> +      return this.gifs.length > 0
Mais si on reçoit bien un résultat et qu'il est vide ?

2017-04-23 09:44 UTC, ptitFicus commented on resources/assets/js/components/SearchResult.vue
> +      return this.gifs.length > 0
Tu as raison, je vais plutôt utiliser `null`.

2017-04-23 09:44 UTC, ptitFicus commented on resources/assets/js/components/Application.vue
> +      console.log(`starting search for ${searchTerm}`)
Tout à fait, je m'en occupe !

2017-04-25 07:31 UTC, frinyvonnick approved these changes
👍

2017-04-25 07:35 UTC, merged