Favorites
frinyvonnick/laragif pull request #24
Opened 2017-05-10 12:23 UTC by ptitFicus

2017-05-10 20:39 UTC, frinyvonnick requested changes

2017-05-10 20:39 UTC, frinyvonnick commented on app/Gif.php
> +    function __construct()
Le constructeur est pas utile ici 😄

2017-05-10 20:39 UTC, frinyvonnick commented on app/Http/Controllers/GifsController.php
> +            $go = new Gif;
Ce serait pas mieux un constructeur à deux paramètres qui initialize starred à false par défaut ?

2017-05-11 07:50 UTC, ptitFicus commented on app/Http/Controllers/GifsController.php
> +            $go = new Gif;
Si clairement, je vais changer

2017-05-11 18:29 UTC, frinyvonnick approved these changes

2017-05-11 19:56 UTC, merged