Broadcasting
frinyvonnick/laragif pull request #35
Opened 2017-05-29 23:12 UTC by ptitFicus

2017-05-30 09:23 UTC, frinyvonnick requested changes

2017-05-30 09:23 UTC, frinyvonnick commented on app/Repositories/GiphyRepository.php
> +            Guzzle::get(self::GIPHY_API . '/random?api_key=' . self::API_KEY, ['connect_timeout' => 10]);
C'est énorme 10 secondes 😕

2017-05-30 09:23 UTC, frinyvonnick commented on resources/assets/js/app.js
> +     host: '127.0.0.1:6001'
Peut être variabiliser l'host ?

2017-05-30 09:23 UTC, frinyvonnick commented on resources/assets/js/app.js
> +console.log(window.location.hostname)
?

2017-05-30 13:27 UTC, ptitFicus commented on resources/assets/js/app.js
> +console.log(window.location.hostname)
Oups

2017-05-30 13:28 UTC, ptitFicus commented on resources/assets/js/app.js
> +     host: '127.0.0.1:6001'
Oui c'était pour être sûr de jamais mocker en dev, je vais rectifier

2017-05-30 13:28 UTC, ptitFicus commented on app/Repositories/GiphyRepository.php
> +            Guzzle::get(self::GIPHY_API . '/random?api_key=' . self::API_KEY, ['connect_timeout' => 10]);
Oui c'était pour être sûr de jamais mocker en dev, je vais modifier

2017-05-30 13:28 UTC, ptitFicus commented on resources/assets/js/app.js
> +     host: '127.0.0.1:6001'
Yes je vais essayer avec window.location.hostname

2017-05-31 08:01 UTC, frinyvonnick requested changes

2017-05-31 08:01 UTC, frinyvonnick commented on resources/assets/js/app.js
> +     host: `${window.location.hostname}:6001`
Il faudrait variabiliser aussi le port ❓

2017-06-03 10:32 UTC, frinyvonnick approved these changes

2017-06-03 11:08 UTC, merged